### ISSUE TITLE
logger image should include SHA tag of latest built image from main branch of cwm-worker-logger

### ISSUE THREAD

**Issue by OriHoch** [CloudWebManage/cwm-worker-deployment-minio#7]
This is a sugested workflow but you can implement in another way if you prefer:

* on push to main branch of cwm-worker-logger repository
* update a file in cwm-worker-deployment-minio repository (e.g. helm/cwm-worker-logger-image.txt) containing the full image name of cwm-worker-logger including the SHA tag that was built
* this update will push a commit to cwm-worker-deployment-minio repository which will trigger the next step
* on push to main branch of cwm-worker-deployment-minio repository
* after the following line in CI: https://github.com/CloudWebManage/cwm-worker-deployment-minio/blob/main/.github/workflows/ci.yml#L48
* add another sed command which will replace the cwm-worker-logger image in values.yaml with the value from helm/cwm-worker-logger-image.txt

**Comment by iamAzeem** [comment]
Added via #12 and https://github.com/CloudWebManage/cwm-worker-logger/pull/10.
